[tool.poetry]
name = "telehram-bot"
version = "0.1.0"
description = ""
authors = ["Maite Puerta Beldarrain <mpuerta004@deusto.es>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
